
(* File generated by ${QMCCHEM_PATH}/scripts/create_properties.py. Do not
   modify here
 *)

type t =
| Cpu
| Wall
| Accep
| Ci_dress
| Ci_dress_mu
| Ci_h_matrix
| Ci_h_matrix_diag
| Ci_h_psidet
| Ci_h_transcor_psi
| Ci_overlap_matrix
| Ci_overlap_psidet
| Dipole
| Drift_mod
| E_kin
| E_loc
| E_loc_zv
| E_nucl
| E_nucl_elec
| E_pot
| Eff_pot_deriv_mu
| Eff_pot_deriv_mu_elec
| Eff_pot_mu
| Eff_pot_mu_elec
| Eff_pot_mu_simple
| Emudiff
| Energy_mu
| Pop_weight
| Psi_norm
| Three_body_mu
| Wf_extension
| Ci_dress_qmcvar
| Ci_dress_mu_qmcvar
| Ci_h_matrix_qmcvar
| Ci_h_matrix_diag_qmcvar
| Ci_h_psidet_qmcvar
| Ci_h_transcor_psi_qmcvar
| Ci_overlap_matrix_qmcvar
| Ci_overlap_psidet_qmcvar
| Dipole_qmcvar
| Drift_mod_qmcvar
| E_kin_qmcvar
| E_loc_qmcvar
| E_loc_zv_qmcvar
| E_nucl_qmcvar
| E_nucl_elec_qmcvar
| E_pot_qmcvar
| Eff_pot_deriv_mu_qmcvar
| Eff_pot_deriv_mu_elec_qmcvar
| Eff_pot_mu_qmcvar
| Eff_pot_mu_elec_qmcvar
| Eff_pot_mu_simple_qmcvar
| Emudiff_qmcvar
| Energy_mu_qmcvar
| Pop_weight_qmcvar
| Psi_norm_qmcvar
| Three_body_mu_qmcvar
| Wf_extension_qmcvar
;;

let calc = function
| Cpu 
| Wall
| Accep -> true
| Ci_dress
| Ci_dress_qmcvar -> 
    begin
      if (Ezfio.has_properties_ci_dress ()) then
        Ezfio.get_properties_ci_dress ()
      else
        false
    end

| Ci_dress_mu
| Ci_dress_mu_qmcvar -> 
    begin
      if (Ezfio.has_properties_ci_dress_mu ()) then
        Ezfio.get_properties_ci_dress_mu ()
      else
        false
    end

| Ci_h_matrix
| Ci_h_matrix_qmcvar -> 
    begin
      if (Ezfio.has_properties_ci_h_matrix ()) then
        Ezfio.get_properties_ci_h_matrix ()
      else
        false
    end

| Ci_h_matrix_diag
| Ci_h_matrix_diag_qmcvar -> 
    begin
      if (Ezfio.has_properties_ci_h_matrix_diag ()) then
        Ezfio.get_properties_ci_h_matrix_diag ()
      else
        false
    end

| Ci_h_psidet
| Ci_h_psidet_qmcvar -> 
    begin
      if (Ezfio.has_properties_ci_h_psidet ()) then
        Ezfio.get_properties_ci_h_psidet ()
      else
        false
    end

| Ci_h_transcor_psi
| Ci_h_transcor_psi_qmcvar -> 
    begin
      if (Ezfio.has_properties_ci_h_transcor_psi ()) then
        Ezfio.get_properties_ci_h_transcor_psi ()
      else
        false
    end

| Ci_overlap_matrix
| Ci_overlap_matrix_qmcvar -> 
    begin
      if (Ezfio.has_properties_ci_overlap_matrix ()) then
        Ezfio.get_properties_ci_overlap_matrix ()
      else
        false
    end

| Ci_overlap_psidet
| Ci_overlap_psidet_qmcvar -> 
    begin
      if (Ezfio.has_properties_ci_overlap_psidet ()) then
        Ezfio.get_properties_ci_overlap_psidet ()
      else
        false
    end

| Dipole
| Dipole_qmcvar -> 
    begin
      if (Ezfio.has_properties_dipole ()) then
        Ezfio.get_properties_dipole ()
      else
        false
    end

| Drift_mod
| Drift_mod_qmcvar -> 
    begin
      if (Ezfio.has_properties_drift_mod ()) then
        Ezfio.get_properties_drift_mod ()
      else
        false
    end

| E_kin
| E_kin_qmcvar -> 
    begin
      if (Ezfio.has_properties_e_kin ()) then
        Ezfio.get_properties_e_kin ()
      else
        false
    end

| E_loc
| E_loc_qmcvar -> 
    begin
      if (Ezfio.has_properties_e_loc ()) then
        Ezfio.get_properties_e_loc ()
      else
        true
    end

| E_loc_zv
| E_loc_zv_qmcvar -> 
    begin
      if (Ezfio.has_properties_e_loc_zv ()) then
        Ezfio.get_properties_e_loc_zv ()
      else
        false
    end

| E_nucl
| E_nucl_qmcvar -> 
    begin
      if (Ezfio.has_properties_e_nucl ()) then
        Ezfio.get_properties_e_nucl ()
      else
        false
    end

| E_nucl_elec
| E_nucl_elec_qmcvar -> 
    begin
      if (Ezfio.has_properties_e_nucl_elec ()) then
        Ezfio.get_properties_e_nucl_elec ()
      else
        false
    end

| E_pot
| E_pot_qmcvar -> 
    begin
      if (Ezfio.has_properties_e_pot ()) then
        Ezfio.get_properties_e_pot ()
      else
        false
    end

| Eff_pot_deriv_mu
| Eff_pot_deriv_mu_qmcvar -> 
    begin
      if (Ezfio.has_properties_eff_pot_deriv_mu ()) then
        Ezfio.get_properties_eff_pot_deriv_mu ()
      else
        false
    end

| Eff_pot_deriv_mu_elec
| Eff_pot_deriv_mu_elec_qmcvar -> 
    begin
      if (Ezfio.has_properties_eff_pot_deriv_mu_elec ()) then
        Ezfio.get_properties_eff_pot_deriv_mu_elec ()
      else
        false
    end

| Eff_pot_mu
| Eff_pot_mu_qmcvar -> 
    begin
      if (Ezfio.has_properties_eff_pot_mu ()) then
        Ezfio.get_properties_eff_pot_mu ()
      else
        false
    end

| Eff_pot_mu_elec
| Eff_pot_mu_elec_qmcvar -> 
    begin
      if (Ezfio.has_properties_eff_pot_mu_elec ()) then
        Ezfio.get_properties_eff_pot_mu_elec ()
      else
        false
    end

| Eff_pot_mu_simple
| Eff_pot_mu_simple_qmcvar -> 
    begin
      if (Ezfio.has_properties_eff_pot_mu_simple ()) then
        Ezfio.get_properties_eff_pot_mu_simple ()
      else
        false
    end

| Emudiff
| Emudiff_qmcvar -> 
    begin
      if (Ezfio.has_properties_emudiff ()) then
        Ezfio.get_properties_emudiff ()
      else
        false
    end

| Energy_mu
| Energy_mu_qmcvar -> 
    begin
      if (Ezfio.has_properties_energy_mu ()) then
        Ezfio.get_properties_energy_mu ()
      else
        false
    end

| Pop_weight
| Pop_weight_qmcvar -> 
    begin
      if (Ezfio.has_properties_pop_weight ()) then
        Ezfio.get_properties_pop_weight ()
      else
        false
    end

| Psi_norm
| Psi_norm_qmcvar -> 
    begin
      if (Ezfio.has_properties_psi_norm ()) then
        Ezfio.get_properties_psi_norm ()
      else
        false
    end

| Three_body_mu
| Three_body_mu_qmcvar -> 
    begin
      if (Ezfio.has_properties_three_body_mu ()) then
        Ezfio.get_properties_three_body_mu ()
      else
        false
    end

| Wf_extension
| Wf_extension_qmcvar -> 
    begin
      if (Ezfio.has_properties_wf_extension ()) then
        Ezfio.get_properties_wf_extension ()
      else
        false
    end

;;

let u _ = ();;

let set_calc = function
| Cpu 
| Wall
| Accep -> u
| Ci_dress 
| Ci_dress_qmcvar -> 
      Ezfio.set_properties_ci_dress 

| Ci_dress_mu 
| Ci_dress_mu_qmcvar -> 
      Ezfio.set_properties_ci_dress_mu 

| Ci_h_matrix 
| Ci_h_matrix_qmcvar -> 
      Ezfio.set_properties_ci_h_matrix 

| Ci_h_matrix_diag 
| Ci_h_matrix_diag_qmcvar -> 
      Ezfio.set_properties_ci_h_matrix_diag 

| Ci_h_psidet 
| Ci_h_psidet_qmcvar -> 
      Ezfio.set_properties_ci_h_psidet 

| Ci_h_transcor_psi 
| Ci_h_transcor_psi_qmcvar -> 
      Ezfio.set_properties_ci_h_transcor_psi 

| Ci_overlap_matrix 
| Ci_overlap_matrix_qmcvar -> 
      Ezfio.set_properties_ci_overlap_matrix 

| Ci_overlap_psidet 
| Ci_overlap_psidet_qmcvar -> 
      Ezfio.set_properties_ci_overlap_psidet 

| Dipole 
| Dipole_qmcvar -> 
      Ezfio.set_properties_dipole 

| Drift_mod 
| Drift_mod_qmcvar -> 
      Ezfio.set_properties_drift_mod 

| E_kin 
| E_kin_qmcvar -> 
      Ezfio.set_properties_e_kin 

| E_loc 
| E_loc_qmcvar -> 
      Ezfio.set_properties_e_loc 

| E_loc_zv 
| E_loc_zv_qmcvar -> 
      Ezfio.set_properties_e_loc_zv 

| E_nucl 
| E_nucl_qmcvar -> 
      Ezfio.set_properties_e_nucl 

| E_nucl_elec 
| E_nucl_elec_qmcvar -> 
      Ezfio.set_properties_e_nucl_elec 

| E_pot 
| E_pot_qmcvar -> 
      Ezfio.set_properties_e_pot 

| Eff_pot_deriv_mu 
| Eff_pot_deriv_mu_qmcvar -> 
      Ezfio.set_properties_eff_pot_deriv_mu 

| Eff_pot_deriv_mu_elec 
| Eff_pot_deriv_mu_elec_qmcvar -> 
      Ezfio.set_properties_eff_pot_deriv_mu_elec 

| Eff_pot_mu 
| Eff_pot_mu_qmcvar -> 
      Ezfio.set_properties_eff_pot_mu 

| Eff_pot_mu_elec 
| Eff_pot_mu_elec_qmcvar -> 
      Ezfio.set_properties_eff_pot_mu_elec 

| Eff_pot_mu_simple 
| Eff_pot_mu_simple_qmcvar -> 
      Ezfio.set_properties_eff_pot_mu_simple 

| Emudiff 
| Emudiff_qmcvar -> 
      Ezfio.set_properties_emudiff 

| Energy_mu 
| Energy_mu_qmcvar -> 
      Ezfio.set_properties_energy_mu 

| Pop_weight 
| Pop_weight_qmcvar -> 
      Ezfio.set_properties_pop_weight 

| Psi_norm 
| Psi_norm_qmcvar -> 
      Ezfio.set_properties_psi_norm 

| Three_body_mu 
| Three_body_mu_qmcvar -> 
      Ezfio.set_properties_three_body_mu 

| Wf_extension 
| Wf_extension_qmcvar -> 
      Ezfio.set_properties_wf_extension 

;;

let of_string s = 
  match (String.lowercase_ascii s) with 
  | "cpu" -> Cpu
  | "wall" -> Wall
  | "accep" -> Accep
  | "ci_dress" -> Ci_dress
  | "ci_dress_mu" -> Ci_dress_mu
  | "ci_h_matrix" -> Ci_h_matrix
  | "ci_h_matrix_diag" -> Ci_h_matrix_diag
  | "ci_h_psidet" -> Ci_h_psidet
  | "ci_h_transcor_psi" -> Ci_h_transcor_psi
  | "ci_overlap_matrix" -> Ci_overlap_matrix
  | "ci_overlap_psidet" -> Ci_overlap_psidet
  | "dipole" -> Dipole
  | "drift_mod" -> Drift_mod
  | "e_kin" -> E_kin
  | "e_loc" -> E_loc
  | "e_loc_zv" -> E_loc_zv
  | "e_nucl" -> E_nucl
  | "e_nucl_elec" -> E_nucl_elec
  | "e_pot" -> E_pot
  | "eff_pot_deriv_mu" -> Eff_pot_deriv_mu
  | "eff_pot_deriv_mu_elec" -> Eff_pot_deriv_mu_elec
  | "eff_pot_mu" -> Eff_pot_mu
  | "eff_pot_mu_elec" -> Eff_pot_mu_elec
  | "eff_pot_mu_simple" -> Eff_pot_mu_simple
  | "emudiff" -> Emudiff
  | "energy_mu" -> Energy_mu
  | "pop_weight" -> Pop_weight
  | "psi_norm" -> Psi_norm
  | "three_body_mu" -> Three_body_mu
  | "wf_extension" -> Wf_extension
  | "ci_dress_qmcvar" -> Ci_dress_qmcvar
  | "ci_dress_mu_qmcvar" -> Ci_dress_mu_qmcvar
  | "ci_h_matrix_qmcvar" -> Ci_h_matrix_qmcvar
  | "ci_h_matrix_diag_qmcvar" -> Ci_h_matrix_diag_qmcvar
  | "ci_h_psidet_qmcvar" -> Ci_h_psidet_qmcvar
  | "ci_h_transcor_psi_qmcvar" -> Ci_h_transcor_psi_qmcvar
  | "ci_overlap_matrix_qmcvar" -> Ci_overlap_matrix_qmcvar
  | "ci_overlap_psidet_qmcvar" -> Ci_overlap_psidet_qmcvar
  | "dipole_qmcvar" -> Dipole_qmcvar
  | "drift_mod_qmcvar" -> Drift_mod_qmcvar
  | "e_kin_qmcvar" -> E_kin_qmcvar
  | "e_loc_qmcvar" -> E_loc_qmcvar
  | "e_loc_zv_qmcvar" -> E_loc_zv_qmcvar
  | "e_nucl_qmcvar" -> E_nucl_qmcvar
  | "e_nucl_elec_qmcvar" -> E_nucl_elec_qmcvar
  | "e_pot_qmcvar" -> E_pot_qmcvar
  | "eff_pot_deriv_mu_qmcvar" -> Eff_pot_deriv_mu_qmcvar
  | "eff_pot_deriv_mu_elec_qmcvar" -> Eff_pot_deriv_mu_elec_qmcvar
  | "eff_pot_mu_qmcvar" -> Eff_pot_mu_qmcvar
  | "eff_pot_mu_elec_qmcvar" -> Eff_pot_mu_elec_qmcvar
  | "eff_pot_mu_simple_qmcvar" -> Eff_pot_mu_simple_qmcvar
  | "emudiff_qmcvar" -> Emudiff_qmcvar
  | "energy_mu_qmcvar" -> Energy_mu_qmcvar
  | "pop_weight_qmcvar" -> Pop_weight_qmcvar
  | "psi_norm_qmcvar" -> Psi_norm_qmcvar
  | "three_body_mu_qmcvar" -> Three_body_mu_qmcvar
  | "wf_extension_qmcvar" -> Wf_extension_qmcvar
  | p -> failwith ("unknown property "^p) ;;


let to_string = function
| Cpu -> "Cpu"
| Wall -> "Wall"
| Accep -> "Accep" 
| Ci_dress -> "Ci_dress" 
| Ci_dress_mu -> "Ci_dress_mu" 
| Ci_h_matrix -> "Ci_h_matrix" 
| Ci_h_matrix_diag -> "Ci_h_matrix_diag" 
| Ci_h_psidet -> "Ci_h_psidet" 
| Ci_h_transcor_psi -> "Ci_h_transcor_psi" 
| Ci_overlap_matrix -> "Ci_overlap_matrix" 
| Ci_overlap_psidet -> "Ci_overlap_psidet" 
| Dipole -> "Dipole" 
| Drift_mod -> "Drift_mod" 
| E_kin -> "E_kin" 
| E_loc -> "E_loc" 
| E_loc_zv -> "E_loc_zv" 
| E_nucl -> "E_nucl" 
| E_nucl_elec -> "E_nucl_elec" 
| E_pot -> "E_pot" 
| Eff_pot_deriv_mu -> "Eff_pot_deriv_mu" 
| Eff_pot_deriv_mu_elec -> "Eff_pot_deriv_mu_elec" 
| Eff_pot_mu -> "Eff_pot_mu" 
| Eff_pot_mu_elec -> "Eff_pot_mu_elec" 
| Eff_pot_mu_simple -> "Eff_pot_mu_simple" 
| Emudiff -> "Emudiff" 
| Energy_mu -> "Energy_mu" 
| Pop_weight -> "Pop_weight" 
| Psi_norm -> "Psi_norm" 
| Three_body_mu -> "Three_body_mu" 
| Wf_extension -> "Wf_extension" 
| Ci_dress_qmcvar -> "Ci_dress_qmcvar" 
| Ci_dress_mu_qmcvar -> "Ci_dress_mu_qmcvar" 
| Ci_h_matrix_qmcvar -> "Ci_h_matrix_qmcvar" 
| Ci_h_matrix_diag_qmcvar -> "Ci_h_matrix_diag_qmcvar" 
| Ci_h_psidet_qmcvar -> "Ci_h_psidet_qmcvar" 
| Ci_h_transcor_psi_qmcvar -> "Ci_h_transcor_psi_qmcvar" 
| Ci_overlap_matrix_qmcvar -> "Ci_overlap_matrix_qmcvar" 
| Ci_overlap_psidet_qmcvar -> "Ci_overlap_psidet_qmcvar" 
| Dipole_qmcvar -> "Dipole_qmcvar" 
| Drift_mod_qmcvar -> "Drift_mod_qmcvar" 
| E_kin_qmcvar -> "E_kin_qmcvar" 
| E_loc_qmcvar -> "E_loc_qmcvar" 
| E_loc_zv_qmcvar -> "E_loc_zv_qmcvar" 
| E_nucl_qmcvar -> "E_nucl_qmcvar" 
| E_nucl_elec_qmcvar -> "E_nucl_elec_qmcvar" 
| E_pot_qmcvar -> "E_pot_qmcvar" 
| Eff_pot_deriv_mu_qmcvar -> "Eff_pot_deriv_mu_qmcvar" 
| Eff_pot_deriv_mu_elec_qmcvar -> "Eff_pot_deriv_mu_elec_qmcvar" 
| Eff_pot_mu_qmcvar -> "Eff_pot_mu_qmcvar" 
| Eff_pot_mu_elec_qmcvar -> "Eff_pot_mu_elec_qmcvar" 
| Eff_pot_mu_simple_qmcvar -> "Eff_pot_mu_simple_qmcvar" 
| Emudiff_qmcvar -> "Emudiff_qmcvar" 
| Energy_mu_qmcvar -> "Energy_mu_qmcvar" 
| Pop_weight_qmcvar -> "Pop_weight_qmcvar" 
| Psi_norm_qmcvar -> "Psi_norm_qmcvar" 
| Three_body_mu_qmcvar -> "Three_body_mu_qmcvar" 
| Wf_extension_qmcvar -> "Wf_extension_qmcvar" 
;;

let of_bytes x = 
   Bytes.to_string x
   |> of_string

let to_bytes x = 
   to_string x
   |> Bytes.of_string


let is_scalar = function
| Cpu -> true
| Wall -> true
| Accep -> true 
| Ci_dress | Ci_dress_qmcvar -> false 
| Ci_dress_mu | Ci_dress_mu_qmcvar -> false 
| Ci_h_matrix | Ci_h_matrix_qmcvar -> false 
| Ci_h_matrix_diag | Ci_h_matrix_diag_qmcvar -> false 
| Ci_h_psidet | Ci_h_psidet_qmcvar -> false 
| Ci_h_transcor_psi | Ci_h_transcor_psi_qmcvar -> false 
| Ci_overlap_matrix | Ci_overlap_matrix_qmcvar -> false 
| Ci_overlap_psidet | Ci_overlap_psidet_qmcvar -> false 
| Dipole | Dipole_qmcvar -> false 
| Drift_mod | Drift_mod_qmcvar -> false 
| E_kin | E_kin_qmcvar -> true 
| E_loc | E_loc_qmcvar -> true 
| E_loc_zv | E_loc_zv_qmcvar -> true 
| E_nucl | E_nucl_qmcvar -> true 
| E_nucl_elec | E_nucl_elec_qmcvar -> true 
| E_pot | E_pot_qmcvar -> true 
| Eff_pot_deriv_mu | Eff_pot_deriv_mu_qmcvar -> true 
| Eff_pot_deriv_mu_elec | Eff_pot_deriv_mu_elec_qmcvar -> false 
| Eff_pot_mu | Eff_pot_mu_qmcvar -> true 
| Eff_pot_mu_elec | Eff_pot_mu_elec_qmcvar -> false 
| Eff_pot_mu_simple | Eff_pot_mu_simple_qmcvar -> true 
| Emudiff | Emudiff_qmcvar -> true 
| Energy_mu | Energy_mu_qmcvar -> true 
| Pop_weight | Pop_weight_qmcvar -> true 
| Psi_norm | Psi_norm_qmcvar -> true 
| Three_body_mu | Three_body_mu_qmcvar -> true 
| Wf_extension | Wf_extension_qmcvar -> true 
;;


let all = [ Cpu ; Wall ; Accep ; 
 Ci_dress ;  Ci_dress_mu ;  Ci_h_matrix ;  Ci_h_matrix_diag ;  Ci_h_psidet ;  Ci_h_transcor_psi ;  Ci_overlap_matrix ;  Ci_overlap_psidet ;  Dipole ;  Drift_mod ;  E_kin ;  E_loc ;  E_loc_zv ;  E_nucl ;  E_nucl_elec ;  E_pot ;  Eff_pot_deriv_mu ;  Eff_pot_deriv_mu_elec ;  Eff_pot_mu ;  Eff_pot_mu_elec ;  Eff_pot_mu_simple ;  Emudiff ;  Energy_mu ;  Pop_weight ;  Psi_norm ;  Three_body_mu ;  Wf_extension ; ];;
